// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mixmatchresttest.domain;

import de.metafinanz.mixmatchresttest.domain.UserEDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserEDataOnDemand_Roo_Configurable {
    
    declare @type: UserEDataOnDemand: @Configurable;
    
}
