// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mixmatchresttest.domain;

import de.metafinanz.mixmatchresttest.domain.UserE;
import de.metafinanz.mixmatchresttest.domain.UserEDataOnDemand;
import de.metafinanz.mixmatchresttest.domain.UserEIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserEIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserEIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserEIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserEIntegrationTest: @Transactional;
    
    @Autowired
    UserEDataOnDemand UserEIntegrationTest.dod;
    
    @Test
    public void UserEIntegrationTest.testCountUserEs() {
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", dod.getRandomUserE());
        long count = UserE.countUserEs();
        Assert.assertTrue("Counter for 'UserE' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserEIntegrationTest.testFindUserE() {
        UserE obj = dod.getRandomUserE();
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserE' failed to provide an identifier", id);
        obj = UserE.findUserE(id);
        Assert.assertNotNull("Find method for 'UserE' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserE' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserEIntegrationTest.testFindAllUserEs() {
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", dod.getRandomUserE());
        long count = UserE.countUserEs();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserE', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserE> result = UserE.findAllUserEs();
        Assert.assertNotNull("Find all method for 'UserE' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserE' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserEIntegrationTest.testFindUserEEntries() {
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", dod.getRandomUserE());
        long count = UserE.countUserEs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserE> result = UserE.findUserEEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserE' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserE' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserEIntegrationTest.testFlush() {
        UserE obj = dod.getRandomUserE();
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserE' failed to provide an identifier", id);
        obj = UserE.findUserE(id);
        Assert.assertNotNull("Find method for 'UserE' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserE(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserE' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserEIntegrationTest.testMergeUpdate() {
        UserE obj = dod.getRandomUserE();
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserE' failed to provide an identifier", id);
        obj = UserE.findUserE(id);
        boolean modified =  dod.modifyUserE(obj);
        Integer currentVersion = obj.getVersion();
        UserE merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserE' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserEIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", dod.getRandomUserE());
        UserE obj = dod.getNewTransientUserE(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserE' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserE' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UserE' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserEIntegrationTest.testRemove() {
        UserE obj = dod.getRandomUserE();
        Assert.assertNotNull("Data on demand for 'UserE' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserE' failed to provide an identifier", id);
        obj = UserE.findUserE(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserE' with identifier '" + id + "'", UserE.findUserE(id));
    }
    
}
