// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mixmatchresttest.domain;

import de.metafinanz.mixmatchresttest.domain.UserE;
import de.metafinanz.mixmatchresttest.domain.UserEDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserEDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserEDataOnDemand: @Component;
    
    private Random UserEDataOnDemand.rnd = new SecureRandom();
    
    private List<UserE> UserEDataOnDemand.data;
    
    public UserE UserEDataOnDemand.getNewTransientUserE(int index) {
        UserE obj = new UserE();
        setUsername(obj, index);
        return obj;
    }
    
    public void UserEDataOnDemand.setUsername(UserE obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public UserE UserEDataOnDemand.getSpecificUserE(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserE obj = data.get(index);
        Long id = obj.getId();
        return UserE.findUserE(id);
    }
    
    public UserE UserEDataOnDemand.getRandomUserE() {
        init();
        UserE obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserE.findUserE(id);
    }
    
    public boolean UserEDataOnDemand.modifyUserE(UserE obj) {
        return false;
    }
    
    public void UserEDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserE.findUserEEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserE' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserE>();
        for (int i = 0; i < 10; i++) {
            UserE obj = getNewTransientUserE(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
