// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Appointment_Roo_Configurable {
    
    declare @type: Appointment: @Configurable;
    
}
