// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import javax.persistence.Entity;

privileged aspect Canteen_Roo_Jpa_Entity {
    
    declare @type: Canteen: @Entity;
    
}
