// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mixmatchresttest.domain;

import de.metafinanz.mixmatchresttest.domain.UserE;

privileged aspect UserE_Roo_JavaBean {
    
    public String UserE.getUsername() {
        return this.username;
    }
    
    public void UserE.setUsername(String username) {
        this.username = username;
    }
    
}
