// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import de.metafinanz.mam.backend.repository.AppointmentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppointmentIntegrationTest_Roo_Configurable {
    
    declare @type: AppointmentIntegrationTest: @Configurable;
    
}
