// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import de.metafinanz.mam.backend.repository.Appointment;
import de.metafinanz.mam.backend.repository.AppointmentDataOnDemand;
import de.metafinanz.mam.backend.repository.AppointmentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppointmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppointmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppointmentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppointmentIntegrationTest: @Transactional;
    
    @Autowired
    AppointmentDataOnDemand AppointmentIntegrationTest.dod;
    
    @Test
    public void AppointmentIntegrationTest.testCountAppointments() {
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", dod.getRandomAppointment());
        long count = Appointment.countAppointments();
        Assert.assertTrue("Counter for 'Appointment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppointmentIntegrationTest.testFindAppointment() {
        Appointment obj = dod.getRandomAppointment();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", obj);
        Long id = obj.getAppointmentID();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to provide an identifier", id);
        obj = Appointment.findAppointment(id);
        Assert.assertNotNull("Find method for 'Appointment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Appointment' returned the incorrect identifier", id, obj.getAppointmentID());
    }
    
    @Test
    public void AppointmentIntegrationTest.testFindAllAppointments() {
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", dod.getRandomAppointment());
        long count = Appointment.countAppointments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Appointment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Appointment> result = Appointment.findAllAppointments();
        Assert.assertNotNull("Find all method for 'Appointment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Appointment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppointmentIntegrationTest.testFindAppointmentEntries() {
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", dod.getRandomAppointment());
        long count = Appointment.countAppointments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Appointment> result = Appointment.findAppointmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Appointment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Appointment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppointmentIntegrationTest.testFlush() {
        Appointment obj = dod.getRandomAppointment();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", obj);
        Long id = obj.getAppointmentID();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to provide an identifier", id);
        obj = Appointment.findAppointment(id);
        Assert.assertNotNull("Find method for 'Appointment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppointment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Appointment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppointmentIntegrationTest.testMergeUpdate() {
        Appointment obj = dod.getRandomAppointment();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", obj);
        Long id = obj.getAppointmentID();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to provide an identifier", id);
        obj = Appointment.findAppointment(id);
        boolean modified =  dod.modifyAppointment(obj);
        Integer currentVersion = obj.getVersion();
        Appointment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getAppointmentID(), id);
        Assert.assertTrue("Version for 'Appointment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppointmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", dod.getRandomAppointment());
        Appointment obj = dod.getNewTransientAppointment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Appointment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Appointment' identifier to be null", obj.getAppointmentID());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Appointment' identifier to no longer be null", obj.getAppointmentID());
    }
    
    @Test
    public void AppointmentIntegrationTest.testRemove() {
        Appointment obj = dod.getRandomAppointment();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to initialize correctly", obj);
        Long id = obj.getAppointmentID();
        Assert.assertNotNull("Data on demand for 'Appointment' failed to provide an identifier", id);
        obj = Appointment.findAppointment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Appointment' with identifier '" + id + "'", Appointment.findAppointment(id));
    }
    
}
