// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import de.metafinanz.mam.backend.repository.Appointment;
import de.metafinanz.mam.backend.repository.AppointmentDataOnDemand;
import de.metafinanz.mam.backend.repository.Canteen;
import de.metafinanz.mam.backend.repository.CanteenDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AppointmentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppointmentDataOnDemand: @Component;
    
    private Random AppointmentDataOnDemand.rnd = new SecureRandom();
    
    private List<Appointment> AppointmentDataOnDemand.data;
    
    @Autowired
    CanteenDataOnDemand AppointmentDataOnDemand.canteenDataOnDemand;
    
    public void AppointmentDataOnDemand.setAppointmentDate(Appointment obj, int index) {
        Date appointmentDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setAppointmentDate(appointmentDate);
    }
    
    public void AppointmentDataOnDemand.setCanteen(Appointment obj, int index) {
        Canteen canteen = canteenDataOnDemand.getRandomCanteen();
        obj.setCanteen(canteen);
    }
    
    public void AppointmentDataOnDemand.setRootAppointment(Appointment obj, int index) {
        Appointment rootAppointment = obj;
        obj.setRootAppointment(rootAppointment);
    }
    
    public Appointment AppointmentDataOnDemand.getSpecificAppointment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Appointment obj = data.get(index);
        Long id = obj.getAppointmentID();
        return Appointment.findAppointment(id);
    }
    
    public Appointment AppointmentDataOnDemand.getRandomAppointment() {
        init();
        Appointment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getAppointmentID();
        return Appointment.findAppointment(id);
    }
    
    public boolean AppointmentDataOnDemand.modifyAppointment(Appointment obj) {
        return false;
    }
    
    public void AppointmentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Appointment.findAppointmentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Appointment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Appointment>();
        for (int i = 0; i < 10; i++) {
            Appointment obj = getNewTransientAppointment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
