// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CanteenIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CanteenIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CanteenIntegrationTest: @Transactional;
    
    @Autowired
    CanteenDataOnDemand CanteenIntegrationTest.dod;
    
    @Test
    public void CanteenIntegrationTest.testCountCanteens() {
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", dod.getRandomCanteen());
        long count = Canteen.countCanteens();
        Assert.assertTrue("Counter for 'Canteen' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CanteenIntegrationTest.testFindCanteen() {
        Canteen obj = dod.getRandomCanteen();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to provide an identifier", id);
        obj = Canteen.findCanteen(id);
        Assert.assertNotNull("Find method for 'Canteen' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Canteen' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CanteenIntegrationTest.testFindAllCanteens() {
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", dod.getRandomCanteen());
        long count = Canteen.countCanteens();
        Assert.assertTrue("Too expensive to perform a find all test for 'Canteen', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Canteen> result = Canteen.findAllCanteens();
        Assert.assertNotNull("Find all method for 'Canteen' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Canteen' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CanteenIntegrationTest.testFindCanteenEntries() {
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", dod.getRandomCanteen());
        long count = Canteen.countCanteens();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Canteen> result = Canteen.findCanteenEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Canteen' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Canteen' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CanteenIntegrationTest.testFlush() {
        Canteen obj = dod.getRandomCanteen();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to provide an identifier", id);
        obj = Canteen.findCanteen(id);
        Assert.assertNotNull("Find method for 'Canteen' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCanteen(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Canteen' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CanteenIntegrationTest.testMergeUpdate() {
        Canteen obj = dod.getRandomCanteen();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to provide an identifier", id);
        obj = Canteen.findCanteen(id);
        boolean modified =  dod.modifyCanteen(obj);
        Integer currentVersion = obj.getVersion();
        Canteen merged = (Canteen)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Canteen' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CanteenIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", dod.getRandomCanteen());
        Canteen obj = dod.getNewTransientCanteen(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Canteen' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Canteen' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Canteen' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CanteenIntegrationTest.testRemove() {
        Canteen obj = dod.getRandomCanteen();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Canteen' failed to provide an identifier", id);
        obj = Canteen.findCanteen(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Canteen' with identifier '" + id + "'", Canteen.findCanteen(id));
    }
    
}
