// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.metafinanz.mam.backend.repository;

import de.metafinanz.mam.backend.repository.Office;
import de.metafinanz.mam.backend.repository.OfficeDataOnDemand;
import de.metafinanz.mam.backend.repository.OfficeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OfficeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OfficeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OfficeIntegrationTest: @Transactional;
    
    @Autowired
    OfficeDataOnDemand OfficeIntegrationTest.dod;
    
    @Test
    public void OfficeIntegrationTest.testCountOffices() {
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", dod.getRandomOffice());
        long count = Office.countOffices();
        Assert.assertTrue("Counter for 'Office' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OfficeIntegrationTest.testFindOffice() {
        Office obj = dod.getRandomOffice();
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Office' failed to provide an identifier", id);
        obj = Office.findOffice(id);
        Assert.assertNotNull("Find method for 'Office' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Office' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OfficeIntegrationTest.testFindAllOffices() {
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", dod.getRandomOffice());
        long count = Office.countOffices();
        Assert.assertTrue("Too expensive to perform a find all test for 'Office', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Office> result = Office.findAllOffices();
        Assert.assertNotNull("Find all method for 'Office' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Office' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OfficeIntegrationTest.testFindOfficeEntries() {
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", dod.getRandomOffice());
        long count = Office.countOffices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Office> result = Office.findOfficeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Office' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Office' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OfficeIntegrationTest.testFlush() {
        Office obj = dod.getRandomOffice();
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Office' failed to provide an identifier", id);
        obj = Office.findOffice(id);
        Assert.assertNotNull("Find method for 'Office' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOffice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Office' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfficeIntegrationTest.testMergeUpdate() {
        Office obj = dod.getRandomOffice();
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Office' failed to provide an identifier", id);
        obj = Office.findOffice(id);
        boolean modified =  dod.modifyOffice(obj);
        Integer currentVersion = obj.getVersion();
        Office merged = (Office)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Office' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfficeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", dod.getRandomOffice());
        Office obj = dod.getNewTransientOffice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Office' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Office' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Office' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OfficeIntegrationTest.testRemove() {
        Office obj = dod.getRandomOffice();
        Assert.assertNotNull("Data on demand for 'Office' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Office' failed to provide an identifier", id);
        obj = Office.findOffice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Office' with identifier '" + id + "'", Office.findOffice(id));
    }
    
}
